// src/components/Card.vue
<script setup lang="ts">
defineProps<{
  isActive: boolean;
  isMatched: boolean;
  text: string;
  value: string;
}>();

// Default values can be set using withDefaults if needed
withDefaults(defineProps<{
  isActive: boolean;
  isMatched: boolean;
  text: string;
  value: string;
}>(), {
  isActive: false,
  isMatched: false,
  text: "",
  value: ""
});
</script>

<template>
  <div 
    class="card"
    :class="{ 
      active: isActive,
      matched: isMatched 
    }"
    @click="$emit('click')"
  >
    {{ text }}
  </div>
</template>

<style scoped>
.card {
    cursor: pointer;
    background-color: #4a90e2;
    color: white;
    border-radius: 8px;
    transition: background-color 0.3s ease;
    padding: 1rem 2rem;
    font-size: 1.2rem;
    display: flex;
    justify-content: center;
    align-items: center;
    user-select: none;
}

.active {
    background-color: #f39c12;
}

.matched {
    background-color: #27ae60;
    cursor: default;
}
</style>

// src/lib/components/Card.svelte
<script lang="ts">
    export let isActive: boolean = false;
    export let isMatched: boolean = false;
    export let text: string = "";
    export const value: string = "";
</script>

<div 
    class="card"
    class:active={isActive}
    class:matched={isMatched}
>
    {text}
</div>

<style>
    .card {
        cursor: pointer;
        background-color: #4a90e2;
        color: white;
        border-radius: 8px;
        transition: background-color 0.3s ease;
        padding: 1rem 2rem;
        font-size: 1.2rem;
        display: flex;
        justify-content: center;
        align-items: center;
        user-select: none;
    }

    .active {
        background-color: #f39c12;
    }

    .matched {
        background-color: #27ae60;
        cursor: default;
    }
</style>
